<?php

namespace App\Commands;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * Processes a CSV file and outputs a PostgreSQL-compatible CREATE TABLE statement.
 */
class CreateTableCommand extends Command
{
    /**
     * Registers the command name, description, and the required `file` argument.
     */
    protected function configure(): void
    {
        $this
            ->setName('create-table')
            ->setDescription('Build CREATE TABLE statement from a CSV file')
            ->addArgument('file', InputArgument::REQUIRED, 'Path to the CSV file (relative or absolute)');
    }

    /**
     * Validates the CSV file, reads its header row, and prints the CREATE TABLE statement.
     * Table name is derived from the filename (without extension).
     */
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        // Validate file and read headers
        $path = $input->getArgument('file');
        if (!$this->validateFile($path, $output)) {
            return Command::FAILURE;
        }

        $handle = fopen($path, 'r');
        if (false === $handle) {
            $output->writeln('<error>Could not open file: '.$path.'</error>');

            return Command::FAILURE;
        }

        $headers = fgetcsv($handle, escape: '\\');
        if (false === $headers) {
            $output->writeln('<error>Could not read headers from file.</error>');

            return Command::FAILURE;
        }
        // Escape headers to be safe
        $headers = array_map(fn (string $h) => $this->escapeName($h), $headers);

        $types = array_fill(0, count($headers), '');  // default type

        // Process data rows.
        while (($data = fgetcsv($handle, escape: '\\')) !== false) {
            // Process row (create INSERT INTO table_name (columns) VALUES (values);)

            // Detect field type
            foreach ($data as $i => $value) {
                $types[$i] = $this->detectType($types[$i], $value);
            }
        }

        fclose($handle);

        // Prepare CREATE TABLE statement
        $tableName = $this->escapeName(pathinfo($path, PATHINFO_FILENAME));
        $columns = "    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n";
        $columns .= implode(",\n", array_map(
            fn (string $col, int $i) => '    '.$col.' '.($types[$i] ?: 'VARCHAR(255)'),
            $headers,
            array_keys($headers)
        ));
        $output->writeln("CREATE TABLE \"{$tableName}\" (\n{$columns}\n);");

        return Command::SUCCESS;
    }

    /**
     * Checks that the path points to an existing file with a .csv extension.
     * Writes an error message and returns false on any validation failure.
     */
    private function validateFile(string $path, OutputInterface $output): bool
    {
        if (!str_ends_with(strtolower($path), '.csv')) {
            $output->writeln('<error>File must have a .csv extension.</error>');

            return false;
        }

        if (!is_file($path)) {
            $output->writeln('<error>File not found: '.$path.'</error>');

            return false;
        }

        return true;
    }

    /**
     * Normalises a CSV header into a safe SQL table name / column name.
     */
    private function escapeName(string $colName): string
    {
        return $colName
        |> trim(...)
        |> strtolower(...)
        |> (fn ($str) => str_replace(' ', '_', $str))
        |> (fn ($str) => preg_replace('/[^a-z0-9_]/', '', $str))  // keep only valid chars
        |> (fn ($str) => ltrim($str, '[0..9_]'))                  // first char must be [a-z]
        |> (fn ($str) => rtrim($str, '_'));                       // last char must be [a-z0-9]
    }

    private function detectType(string $currentType, string $value): string
    {
        if ('' === $value) {
            return $currentType;  // ignore empty values for type detection
        }

        // Detect new type based on value
        if (is_numeric($value)) {
            if (str_contains($value, '.')) {
                $newType = 'DECIMAL';
            } else {
                $newType = 'INT';
            }
        } else {
            $newType = 'VARCHAR(255)';
        }

        if (empty($currentType)) {
            return $newType;  // set type if not set yet
        } elseif ($currentType !== $newType) {
            $newType = 'VARCHAR(255)';  // fallback to string if inconsistent types
        }

        return $newType;
    }
}
